### ISSUE TITLE
'Amount' parameter is int type for CreatePaymentAsync

### ISSUE THREAD

**Issue by dgd22** [CurrencyCloud/currencycloud-net#1]
The API calls for 'amount' using two decimal places, but the method in the SDK expects an int type.

https://github.com/CurrencyCloud/currencycloud-net/blob/a0e6f0ad8c96130d143b52935a682eaf0e220950/Source/CurrencyCloud/Client.cs#L647

**Comment by rjnienaber** [comment]
Hey, thanks for giving us this feedback. We are aware that our first stab at the api had some shortcomings and we're busy updating it. You can see some of our progress [here](https://github.com/ngorinov1/currencycloud-net), including [a fix for the bug](https://github.com/ngorinov1/currencycloud-net/blob/edf39b4cffe70ae3f11b402793fd0f8ee7d57ad4/Source/CurrencyCloud/Entity/Payment.cs#L51) you've pointed out.

We're hoping to merge the changes in soon but any feedback on the new code would be welcomed.

**Comment by rjnienaber** [comment]
This has been fixed as part of pull request #2.
