### ISSUE TITLE
Form data array formatting error

### ISSUE THREAD

**Issue by SkipperRoo** [CurrencyCloud/currencycloud-net#13]
Hi,

I'm using your .Net wrapper for your API and believe that I've bumped into a form data serialisation problem with string arrays (probably any array for that matter).  I've been getting a problem with both the Verify & Create Beneficiary methods when I provide a payment type.

To track this down I've captured the exchange using Fiddle and can see that the payment_types form data is formatted oddly.  

This is my capture below:-

payment_types=payment_types%5B%5D%3Dpriority

It should be:-
payment_types%5B%5D%3Dpriority

In my C# world I'm setting the PaymentType property of the Beneficiary object to something like this:-

verificationBeneficiary.PaymentType = new List<string>(new [] {"priority"});

Hope this all makes sense to you but please do contact me if I can provide any more information.

Kind regards

Andy Lamper

**Comment by aomega08** [comment]
Hi @SkipperRoo and thanks for opening this issue.

We will be investigating in the next few days and let you know about any outcome :)

**Comment by EAddario** [comment]
Fixed in v2.4.3
