### ISSUE TITLE
Polly v7+ not supported

### ISSUE THREAD

**Issue by grigorgeous** [CurrencyCloud/currencycloud-net#29]
There are some major changes was made to Polly v7+ so that your .NET library doesn't work with newer versions of this dependancy.

Here are the details on what has changed and how it can be easily fixed:
https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes

**Comment by EAddario** [comment]
Thanks for the heads up @grigorgeous. Support for Polly v7 as well new endpoints will be available in the next release due this month

**Comment by EAddario** [comment]
Fixed in v5.1.0
