### ISSUE TITLE
on_behalf_of missing in Conversion 

### ISSUE THREAD

**Issue by invetico** [CurrencyCloud/currencycloud-net#31]
When trying to call a conversion via the SDK, we are unable to find the on_behalf_of field.

![image_2019_04_10T06_34_20_316Z](https://user-images.githubusercontent.com/42125621/55882628-31597f80-5be8-11e9-818a-1e083f2b12d2.png)

**Comment by jonathancouchman** [comment]
None of the Entities are supplied with an on_behalf_field directly. There is a function on the Client that will execute operations on behalf of another contact. Hence you create a conversion in the normal way, but then execute the creation on behalf of the desired user

see 

https://github.com/CurrencyCloud/currencycloud-net/blob/b26709b621c1ad656a34bdd19ad42d195b7325c7/Source/CurrencyCloud/Client.cs#L251
