### ISSUE TITLE
Retry.Enabled = true breaks InitializeAsync() in CurrencyCloud v4

### ISSUE THREAD

**Issue by grigorgeous** [CurrencyCloud/currencycloud-net#32]
Hi,

I tried to implement your CheckBalance.cs example, and always got the following error:

`*** Check Balance ***
BadRequestException
---
platform: .NET 4.7.2 or later
request:
 parameters: {}
 verb: POST
 url: https://api.currencycloud.com/v2/authenticate/api
response:
 status_code: 400
 date: Fri, 12 Apr 2019 09:36:36 GMT
 request_id: 0cfae549-9074-4bd9-b7ce-7028f59bd323
errors:
- field: login_id
 code: login_id_is_required
 message: login_id is required
 params: {}
- field: login_id
 code: login_id_is_too_short
 message: login_id can not be shorter than 1 character(s)
 params:
   minlength: 1
- field: api_key
 code: api_key_is_required
 message: api_key is required
 params: {}
- field: api_key
 code: api_key_length_is_invalid
 message: api_key should be 64 character(s) long
 params:
   length: 64`

I'm 100% sure I sent login & password with pure strings in this method.
However, my colleague found out that this exists only when "Retry.Enabled" is set to true (as in your examples). Once I changed it to false, everything went smooth. My colleague also claims that 3rd version of your library works just fine in both cases.

Please kindly investigate.

**Comment by EAddario** [comment]
Fixed in v5.1.0
