### ISSUE TITLE
Support for Find Funding Accounts endpoint

### ISSUE THREAD

**Issue by francisrohner** [CurrencyCloud/currencycloud-net#45]
https://www.currencycloud.com/developers/docs/item/find-funding-accounts/

**Comment by jonathancouchman** [comment]
@francisrohner thank you for raising this issue. Adding support for the Funding Accounts API is currently in our backlog and we will be aiming to move it into one of our upcoming sprints very soon. I will update this issue when we are ready to release it.

**Comment by francisrohner** [comment]
This worked: (just might want to remove the bits I've added about display strings)

https://gist.github.com/francisrohner/f0f6530fe60671258d6efa3827492d98

**Comment by jonathancouchman** [comment]
@francisrohner thank you for you input and support. This issue has now been resolved and released as part of [5.3.5](https://github.com/CurrencyCloud/currencycloud-net/releases/tag/v5.3.5)
