### ISSUE TITLE
Missing endpoint /v2/demo/funding/create on .NET SDK

### ISSUE THREAD

**Issue by milancarakovac** [CurrencyCloud/currencycloud-net#83]
It seems that this endpoint is not available on .NET SDK.

**Comment by jonathancouchman** [comment]
That is correct. Since this endpoint is only supported in the demo environment to simulate incoming funds, it has not yet been added to the SDK. We will have an internal discussion on the best approach to making this available

**Comment by milancarakovac** [comment]
OK, thanks
